# Generated by Django 2.1.10 on 2019-08-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredient_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
